include: package:lints/recommended.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
  errors:
    deprecated_member_use_from_same_package: ignore
    todo: ignore
    unintended_html_in_doc_comment: ignore

formatter:
  page_width: 120
  trailing_commas: preserve

linter:
  rules:
    prefer_final_locals: true
    prefer_final_in_for_each: true
    prefer_single_quotes: true
    unnecessary_parenthesis: true
